// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLcs6ODpAEGYxJHDDiAAtejd5SWd1A8SU',
    appId: '1:203641720069:web:d41dd785cce2b51538fb6c',
    messagingSenderId: '203641720069',
    projectId: 'bookmyshow-5452b',
    authDomain: 'bookmyshow-5452b.firebaseapp.com',
    storageBucket: 'bookmyshow-5452b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkq6VH03BDb92_NzDwSy610DvbUxx_UdI',
    appId: '1:203641720069:android:157fcefb8ebebe9038fb6c',
    messagingSenderId: '203641720069',
    projectId: 'bookmyshow-5452b',
    storageBucket: 'bookmyshow-5452b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWP9W0VnuU2FbEmsUoKse_ihmpjPpahbw',
    appId: '1:203641720069:ios:7571316fe4a4947938fb6c',
    messagingSenderId: '203641720069',
    projectId: 'bookmyshow-5452b',
    storageBucket: 'bookmyshow-5452b.firebasestorage.app',
    iosBundleId: 'com.example.bookmyshowFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWP9W0VnuU2FbEmsUoKse_ihmpjPpahbw',
    appId: '1:203641720069:ios:7571316fe4a4947938fb6c',
    messagingSenderId: '203641720069',
    projectId: 'bookmyshow-5452b',
    storageBucket: 'bookmyshow-5452b.firebasestorage.app',
    iosBundleId: 'com.example.bookmyshowFlutter',
  );
}
